level_0 = {
		'terrain': '../levels/0/level_0_terrain.csv',
		'coins': '../levels/0/level_0_coins.csv',
		'trees': '../levels/0/level_0_trees.csv',
		'crates': '../levels/0/level_0_crates.csv',
		'enemies': '../levels/0/level_0_enemies.csv',
		'constraints': '../levels/0/level_0_constraints.csv',
		'player': '../levels/0/level_0_player.csv',
		'grass': '../levels/0/level_0_grass.csv',
		'node_pos': (50,250),
		'unlock': 1,
		'node_graphics': '../graphics/overworld/0'}
level_1 = {
		'terrain': '../levels/1/level_1_terrain.csv',
		'coins': '../levels/1/level_1_coins.csv',
		'trees': '../levels/1/level_1_trees.csv',
		'crates': '../levels/1/level_1_crates.csv',
		'enemies': '../levels/1/level_1_enemies.csv',
		'constraints': '../levels/1/level_1_constraints.csv',
		'player': '../levels/1/level_1_player.csv',
		'grass': '../levels/1/level_1_grass.csv',
		'node_pos': (150,80),
		'unlock': 2,
		'node_graphics': '../graphics/overworld/1'}
level_2 = {
		'terrain': '../levels/2/level_2_terrain.csv',
		'coins': '../levels/2/level_2_coins.csv',
		'trees': '../levels/2/level_2_trees.csv',
		'crates': '../levels/2/level_2_crates.csv',
		'enemies': '../levels/2/level_2_enemies.csv',
		'constraints': '../levels/2/level_2_constraints.csv',
		'player': '../levels/2/level_2_player.csv',
		'grass': '../levels/2/level_2_grass.csv',
		'node_pos': (265,190),
		'unlock': 3,
		'node_graphics': '../graphics/overworld/2'}
level_3 = {
		'terrain': '../levels/3/level_3_terrain.csv',
		'coins': '../levels/3/level_3_coins.csv',
		'trees': '../levels/3/level_3_trees.csv',
		'crates': '../levels/3/level_3_crates.csv',
		'enemies': '../levels/3/level_3_enemies.csv',
		'constraints': '../levels/3/level_3_constraints.csv',
		'player': '../levels/3/level_3_player.csv',
		'grass': '../levels/3/level_3_grass.csv',
		'node_pos': (365,50),
		'unlock': 4,
		'node_graphics': '../graphics/overworld/3'}
level_4 = {
		'terrain': '../levels/4/level_4_terrain.csv',
		'coins': '../levels/4/level_4_coins.csv',
		'trees': '../levels/4/level_4_trees.csv',
		'crates': '../levels/4/level_4_crates.csv',
		'enemies': '../levels/4/level_4_enemies.csv',
		'constraints': '../levels/4/level_4_constraints.csv',
		'player': '../levels/4/level_4_player.csv',
		'grass': '../levels/4/level_4_grass.csv',
		'node_pos': (425,300),
		'unlock': 5,
		'node_graphics': '../graphics/overworld/4'}
level_5 = {
		'terrain': '../levels/5/level_5_terrain.csv',
		'coins': '../levels/5/level_5_coins.csv',
		'trees': '../levels/5/level_5_trees.csv',
		'crates': '../levels/5/level_5_crates.csv',
		'enemies': '../levels/5/level_5_enemies.csv',
		'constraints': '../levels/5/level_5_constraints.csv',
		'player': '../levels/5/level_5_player.csv',
		'grass': '../levels/5/level_5_grass.csv',
		'node_pos': (545,150),
		'unlock': 6,
		'node_graphics': '../graphics/overworld/5'}

levels = {
	0: level_0,
	1: level_1,
	2: level_2,
	3: level_3,
	4: level_4,
	5: level_5}
